{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: child1  # Assumes `child1` is running
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80
{{- end }}

